
# Params
radarRelayRestEndpoint: 'https://api.radarrelay.com/v2'
radarRelayWebSocketEndpoint: 'wss://ws.radarrelay.com/v2'
rpcUrl: 'http://localhost:8545'
wrapThreshold: 0.1 # minimum eth required to trigger a wrap event
gasPrice: 1 # in gwei
#sdkInitializationTimeoutMs: 30000

# If you want to default the wallet password for dev purposes. NOTICE: highly insecure!
# wallet:
#   password: 'mydevpassword'

# Exchanges
exchanges:
  - 'binance'
  - 'poloniex'
  - 'bittrex'

# Maker algorithm params
algo:
  expiration: 3 # in hours
  spread: # spread percentages
    - 0.01
    - 0.03
    - 0.05
    - 0.075
    - 0.11
    - 0.125
    - 0.15
    - 0.2
